spring.application.name=praesens

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/praesens_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate e JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Criação automática das tabelas
spring.jpa.hibernate.ddl-auto=update

